site_name: Suomea Blog
theme:
  favicon: pictures/favicon.svg
  logo: pictures/favicon.svg
  palette:
    primary: red
  font:
    text: Monaco
    code: Monaco
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  feature:
    #    - navigation.instant
    #    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - MySQL:
      - MySQL/MySQL Tips.md
  - K8S:
      - K8S/安装 Kubernetes 集群.md
      - K8S/安装 Kuboard 集群管理界面.md
      - K8S/安装 Nginx Ingress.md
  - Linux:
      - Linux/Linux Tips.md
      - Linux/定时任务.md
      - Linux/定时备份 MySQL.md
      - Linux/磁盘分区.md
      - Linux/Nginx 编译安装.md
  - OS:
      - OS/并发——多线程.md
      - OS/并发——锁.md
      - OS/并发——条件变量.md
      - OS/并发——信号量.md
      - OS/并发——基于并发的数据结构.md
  - Algorithms:
      - Algorithms/求解算数表达式的值.md
      - Algorithms/Base64 算法.md
  - Architecture:
      - Architecture/设备信息.md
  - Arts:
      - Arts/满江红-岳飞.md
      - Arts/侠客行-李白.md
  - Reading:
      - Reading/读书计划.md
      - Reading/2022.md
      - Reading/2021.md

extra_css:
  - stylesheets/extra.css
