site_name: Suomea's Blog
repo_url: https://github.com/Suomea/blog
repo_name: Suomea/blog
theme:
  favicon: LocalFile/favicon.svg
  logo: LocalFile/favicon.svg
  palette: 
    primary: custom
  font:
    text: MiSans
    code: MiSans
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    # - navigation.instant
    # - navigation.tracking
    # - navigation.footer
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - 数据库:
      - MySQL/MySQL Tips.md
      - MySQL/MySQL 安装.md
      - MySQL/MySQL 备份.md
      - MySQL/MySQL 配置主从.md
      - Redis/Redis 安装.md
      - Redis/Redis 数据结构.md
      - DM/达梦安装.md
      - Doris/Doris 接入 Kafka 的数据.md
      - Doris/Doris 接入 MySQL 的数据.md
      - Doris/Doris 日期时间类型.md
  - K8S:
      - K8S/安装 Kubernetes 集群.md
      - K8S/安装 Kuboard 集群管理界面.md
      - K8S/安装 Nginx Ingress.md
  - Linux:
      - Linux/Linux Tips.md
      - Linux/Linux 定时任务.md
      - Linux/Linux 文件系统.md
      - Linux/Linux 磁盘分区.md
      - Linux/Linux 账号群组.md
      - Linux/正则表达式.md
      - Linux/Nginx 编译安装.md
      - Linux/curl.md
  - 计算机网络:
      - Network/Network Tips.md
      - Network/网络层：IP.md
      - Network/网络层：ICMP.md
      - Network/运输层：UDP.md
      - Network/运输层：TCP.md
  - 操作系统:
      - OS/OS Tips.md
      - OS/进程.md
      - OS/线程.md
      - OS/并发控制.md
      - OS/汇编——介绍.md
      - OS/汇编——环境搭建.md
      - OS/C.md
  - 数据结构和算法:
      - Algorithms/求解算数表达式的值.md
      - Algorithms/Base64 算法.md
      - Algorithms/数据结构：图.md
#  - Architecture:
#      - Architecture/设备信息.md
  - 文章:
      - Arts/满江红-岳飞.md
      - Arts/侠客行-李白.md
      - Arts/大观楼长联-孙髯.md
  - 爪哇:
      - Java/并发.md
      - Java/重复提交.md
  - 记录:
      - Reading/Timeline.md
  #     - Reading/2022.md
  #     - Reading/2021.md
  #     - Reading/2023.md

extra_css:
  - stylesheets/extra.css
