site_name: Suomea Blog
theme:
  favicon: pictures/favicon.svg
  logo: pictures/favicon.svg
  palette:
    primary: red
  font:
    text: Monaco
    code: Monaco
  name: material

  feature:
#    - navigation.instant
#    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  features:
     - navigation.tabs
     - navigation.tabs.sticky
     - navigation.top
nav:
  - MySQL:
      - MySQL/MySQL Tips.md
  - K8S:
      - K8S/安装 Kubernetes 集群.md
      - K8S/安装 Kuboard 集群管理界面.md
      - K8S/安装 Nginx Ingress.md
  - Linux:
      - Linux/Linux Tips.md
      - Linux/定时任务.md
      - Linux/定时备份 MySQL.md
      - Linux/磁盘分区.md
      - Linux/Nginx 编译安装.md
  - Reading:
      - Reading/读书计划.md
      - Reading/2022.md
      - Reading/2021.md
